export const GROUP_THEMES = {
  ACTIONS_MOVIES: ["Die Hard", "Terminator", "Matrix", "John Wick", "Mad Max", "Gladiator", "Rocky", "Top Gun", "Rambo", "Predator"],
  APEX_PREDATORS: ["Lions", "Great Whites", "Grizzlies", "Orcas", "Komodo Dragons", "Tigers", "Polar Bears", "Crocodiles", "Jaguars", "Wolves"],
  AVENGERS: ["Iron Man", "Captain America", "Thor", "Hulk", "Black Widow", "Hawkeye", "Spiderman", "Black Panther", "Doctor Strange", "Ant-Man"],
  BAGELS: ["Everything", "Plain", "Sesame", "Poppy", "Cinnamon Raisin", "Blueberry", "Onion", "Garlic", "Pumpernickel", "Whole Wheat"],
  BIRDS_OF_PREY: ["Eagles", "Falcons", "Hawks", "Owls", "Ospreys", "Vultures", "Kestrels", "Condors", "Harriers", "Kites"],
  BOARD_GAMES: ["Monopoly", "Scrabble", "Risk", "Catan", "Clue", "Battleship", "Connect 4", "Candy Land", "Operation", "Twister"],
  BREAKFAST_FOODS: ["Pancakes", "Waffles", "Bacon", "Eggs", "Toast", "Oatmeal", "Yogurt", "Hashbrowns", "Sausage", "Biscuits"],
  CANDY_BARS: ["Snickers", "KitKat", "Twix", "Milky Way", "Hershey", "Reeses", "Butterfinger", "Crunch", "Almond Joy", "3 Musketeers"],
  CAR_BRANDS: ["Ferrari", "Lamborghini", "Porsche", "Bugatti", "McLaren", "Aston Martin", "Maserati", "Bentley", "Rolls Royce", "Tesla"],
  CAT_BREEDS: ["Siamese", "Persian", "Maine Coon", "Bengal", "Sphynx", "Ragdoll", "British Shorthair", "Scottish Fold", "Abyssinian", "Tabby"],
  CEREAL: ["Captain Crunch", "Fruit Loops", "Lucky Charms", "Frosted Flakes", "Cocoa Puffs", "Cinnamon Toast Crunch", "Rice Krispies", "Cookie Crisp", "Apple Jacks", "Trix"],
  CHEESE_TYPES: ["Cheddar", "Mozzarella", "Swiss", "Provolone", "Gouda", "Brie", "Parmesan", "Feta", "Blue", "Monterey Jack"],
  CHESS_PIECES: ["Kings", "Queens", "Rooks", "Bishops", "Knights", "Pawns", "Grandmasters", "Checkmates", "Gambits", "Castles"],
  CITY_NICKNAMES: ["Big Apple", "Windy City", "Sin City", "Motor City", "Big Easy", "Mile High", "Emerald City", "City of Angels", "Beantown", "Music City"],
  CLOUDS: ["Cumulus", "Stratus", "Cirrus", "Nimbus", "Altocumulus", "Cirrostratus", "Cumulonimbus", "Stratocumulus", "Nimbostratus", "Fog"],
  COFFEE_ORDERS: ["Espresso", "Latte", "Cappuccino", "Americano", "Macchiato", "Mocha", "Cold Brew", "Frappuccino", "Flat White", "Cortado"],
  COLORS: ["Neon Blue", "Electric Lime", "Hot Pink", "Cyber Yellow", "Ultra Violet", "Inferno Orange", "Laser Red", "Midnight Black", "Ghost White", "Toxic Green"],
  CONSTELLATIONS: ["Orion", "Ursa Major", "Cassiopeia", "Scorpius", "Pegasus", "Leo", "Gemini", "Taurus", "Andromeda", "Cygnus"],
  CRYPTO_COINS: ["Bitcoin", "Ethereum", "Dogecoin", "Litecoin", "Cardano", "Solana", "Polkadot", "Shiba Inu", "Ripple", "Tether"],
  DESSERTS: ["Brownie", "Cupcake", "Cookie", "Donut", "Pie", "Cheesecake", "Tiramisu", "Gelato", "Pudding", "Muffin"],
  DINOSAURS: ["T-Rex", "Velociraptor", "Triceratops", "Stegosaurus", "Brachiosaurus", "Pterodactyl", "Ankylosaurus", "Spinosaurus", "Allosaurus", "Diplodocus"],
  DISNEY_VILLAINS: ["Jafar", "Ursula", "Scar", "Maleficent", "Hades", "Hook", "Cruella", "Gaston", "Queen of Hearts", "Evil Queen"],
  DOG_BREEDS: ["Golden Retriever", "German Shepherd", "Labrador", "Bulldog", "Beagle", "Poodle", "Husky", "Boxer", "Dachshund", "Pug"],
  ELEMENTS: ["Gold", "Silver", "Iron", "Copper", "Neon", "Helium", "Titanium", "Platinum", "Carbon", "Oxygen"],
  EMOJIS: ["😎", "🔥", "🚀", "💀", "💩", "🤡", "🤠", "👽", "👻", "🤖"],
  FAST_FOOD: ["McDonalds", "Burger King", "Wendys", "Taco Bell", "Chick-fil-A", "Subway", "Dominos", "KFC", "In-N-Out", "Chipotle"],
  FISH_TYPES: ["Shark", "Tuna", "Salmon", "Clownfish", "Swordfish", "Pufferfish", "Stingray", "Goldfish", "Barracuda", "Eel"],
  FLOWERS: ["Rose", "Tulip", "Sunflower", "Daisy", "Lily", "Orchid", "Violet", "Hibiscus", "Lotus", "Jasmine"],
  FORTNITE_LOCATIONS: ["Tilted Towers", "Pleasant Park", "Retail Row", "Greasy Grove", "Salty Springs", "Loot Lake", "Dusty Depot", "Tomato Town", "Risky Reels", "Lazy Links"],
  FRUITS: ["Apple", "Banana", "Orange", "Strawberry", "Grape", "Watermelon", "Pineapple", "Mango", "Peach", "Kiwi"],
  GEMSTONES: ["Diamond", "Ruby", "Emerald", "Sapphire", "Amethyst", "Topaz", "Opal", "Pearl", "Garnet", "Jade"],
  GREEK_GODS: ["Zeus", "Poseidon", "Hades", "Ares", "Athena", "Apollo", "Hermes", "Artemis", "Hephaestus", "Dionysus"],
  HARRY_POTTER: ["Gryffindor", "Slytherin", "Hufflepuff", "Ravenclaw", "Potter", "Weasley", "Malfoy", "Dumbledore", "Hagrid", "Voldemort"],
  HOT_SAUCES: ["Tabasco", "Sriracha", "Cholula", "Franks RedHot", "Texas Pete", "Valentina", "Crystal", "Tapatio", "Ghost Pepper", "Carolina Reaper"],
  ICE_CREAM: ["Vanilla", "Chocolate", "Strawberry", "Mint Chip", "Cookie Dough", "Rocky Road", "Butter Pecan", "Coffee", "Pistachio", "Neapolitan"],
  INSECTS: ["Ants", "Bees", "Butterflies", "Spiders", "Scorpions", "Beetles", "Dragonflies", "Praying Mantis", "Grasshoppers", "Ladybugs"],
  JEDI_MASTERS: ["Yoda", "Obi-Wan", "Mace Windu", "Luke", "Anakin", "Qui-Gon", "Ahsoka", "Rey", "Kylo", "Vader"],
  MARIO_KART: ["Mario", "Luigi", "Bowser", "Peach", "Yoshi", "Toad", "Donkey Kong", "Wario", "Waluigi", "Koopa Troopa"],
  MINECRAFT_MOBS: ["Creeper", "Zombie", "Skeleton", "Enderman", "Spider", "Villager", "Pig", "Cow", "Sheep", "Chicken"],
  MOUNTAINS: ["Everest", "K2", "Kilimanjaro", "Denali", "Fuji", "Rainier", "Matterhorn", "Olympus", "Elbert", "Whitney"],
  NBA_TEAMS: ["Lakers", "Celtics", "Warriors", "Bulls", "Heat", "Knicks", "Nets", "Suns", "Bucks", "Nuggets"],
  NFL_TEAMS: ["Chiefs", "Eagles", "Cowboys", "49ers", "Bengals", "Bills", "Packers", "Steelers", "Ravens", "Vikings"],
  OCEANS: ["Pacific", "Atlantic", "Indian", "Arctic", "Southern", "Caribbean", "Mediterranean", "Baltic", "Red", "Dead"],
  PASTA_SHAPES: ["Spaghetti", "Penne", "Ravioli", "Macaroni", "Fettuccine", "Linguine", "Rotini", "Farfalle", "Rigatoni", "Lasagna"],
  PIZZA_TOPPINGS: ["Pepperoni", "Sausage", "Mushroom", "Onion", "Peppers", "Bacon", "Olive", "Ham", "Pineapple", "Spinach"],
  PLANETS: ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto", "Sun"],
  POKEMON: ["Pikachu", "Charizard", "Squirtle", "Bulbasaur", "Jigglypuff", "Mewtwo", "Gengar", "Snorlax", "Eevee", "Lucario"],
  POTATO_CHIPS: ["Lays", "Ruffles", "Pringles", "Doritos", "Cheetos", "Fritos", "Tostitos", "SunChips", "Bugles", "Takis"],
  RAPPERS: ["Lil Wayne", "Drake", "Kendrick", "J. Cole", "Kanye", "Eminem", "Jay-Z", "Snoop", "Dr. Dre", "Tupac"],
  SHARK_TYPES: ["Great White", "Hammerhead", "Tiger", "Bull", "Mako", "Whale Shark", "Nurse", "Thresher", "Goblin", "Lemon"],
  SHOE_BRANDS: ["Nike", "Adidas", "New Balance", "Saucony", "Brooks", "Hoka", "Asics", "Puma", "Reebok", "Under Armour"],
  SODA_BRANDS: ["Coke", "Pepsi", "Sprite", "Dr Pepper", "Mountain Dew", "Fanta", "Root Beer", "Ginger Ale", "Orange Crush", "7Up"],
  SPACE: ["Supernova", "Black Hole", "Nebula", "Galaxy", "Comet", "Asteroid", "Eclipse", "Pulsar", "Quasar", "Orbit"],
  SPICES: ["Salt", "Pepper", "Garlic", "Cinnamon", "Paprika", "Cumin", "Oregano", "Basil", "Thyme", "Rosemary"],
  STRANGER_THINGS: ["Eleven", "Mike", "Dustin", "Lucas", "Will", "Max", "Steve", "Nancy", "Jonathan", "Hopper"],
  SUSHI_ROLLS: ["California", "Spicy Tuna", "Dragon", "Rainbow", "Philly", "Tempura", "Spider", "Caterpillar", "Avocado", "Salmon"],
  TAYLOR_SWIFT_ERAS: ["Debut", "Fearless", "Speak Now", "Red", "1989", "Reputation", "Lover", "Folklore", "Evermore", "Midnights"],
  TREES: ["Oak", "Pine", "Maple", "Birch", "Willow", "Redwood", "Palm", "Cedar", "Spruce", "Elm"],
  VEGETABLES: ["Carrot", "Broccoli", "Corn", "Potato", "Spinach", "Kale", "Peas", "Beans", "Tomato", "Onion"],
  VIDEO_GAMES: ["Minecraft", "Roblox", "Fortnite", "Call of Duty", "FIFA", "Madden", "Zelda", "Mario", "Halo", "GTA"],
  WEATHER: ["Tornado", "Hurricane", "Blizzard", "Tsunami", "Lightning", "Thunder", "Hail", "Rain", "Snow", "Wind"],
  WWE: ["The Rock", "John Cena", "Undertaker", "Stone Cold", "Hulk Hogan", "Ric Flair", "Rey Mysterio", "Triple H", "Roman Reigns", "Cody Rhodes"],
  ZODIAC_SIGNS: ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn"]
};

export const getRandomTheme = () => {
  const keys = Object.keys(GROUP_THEMES);
  return keys[Math.floor(Math.random() * keys.length)] as keyof typeof GROUP_THEMES;
};